### ISSUE TITLE
Update etaoin pod brew installation

### ISSUE THREAD

**Issue by kiramclean** [borkdude/homebrew-brew#3]
I noticed homebrew still installs the very first version of the babashka etaoin pod (`0.0.1-SNAPSHOT`, from [these instructions](https://github.com/borkdude/homebrew-brew/blob/master/pod-babashka-etaoin.rb). Would it be possible to bump the version to the latest gh release? Happy to attempt a PR if you're open to it.

**Comment by borkdude** [comment]
@kiramclean The recommended way to use the pod is via the pod registry: https://github.com/babashka/pod-registry/blob/master/examples/etaoin.clj. Can you let me know if that works for you?

**Comment by kiramclean** [comment]
Oh that's great! It does work. Sorry, I didn't know about the pod registry. Super cool! Thanks so much. Nevermind this, then.
